# Generated by Django 5.2.7 on 2025-11-04 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeviceActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point', models.CharField(max_length=64)),
                ('button_name', models.CharField(max_length=64)),
                ('last_state', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlhub.device')),
            ],
        ),
    ]
