# Generated by Django 5.2.7 on 2025-11-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlhub', '0002_device_ip_deviceactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceactions',
            old_name='button_name',
            new_name='action_name',
        ),
    ]
