# Generated by Django 5.2.7 on 2025-11-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlhub', '0003_rename_button_name_deviceactions_action_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceActions',
            new_name='DeviceAction',
        ),
    ]
