# Generated by Django 5.2.7 on 2025-11-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlhub', '0004_rename_deviceactions_deviceaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaction',
            name='type',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlhub.deviceaction'),
        ),
    ]
