# Generated by Django 5.2.7 on 2025-11-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlhub', '0005_deviceaction_type_stat_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaction',
            name='stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stat_for_action', to='controlhub.stat'),
        ),
        migrations.AlterField(
            model_name='deviceaction',
            name='type',
            field=models.CharField(choices=[('button', 'Button'), ('sensor', 'Sensor')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_for_stat', to='controlhub.deviceaction'),
        ),
    ]
