# Generated by Django 5.2.7 on 2025-11-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlhub', '0006_deviceaction_stat_alter_deviceaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceaction',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='action',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='device',
        ),
        migrations.AddField(
            model_name='stat',
            name='device_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlhub.deviceaction'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('creator', 'Creator'), ('guest', 'Guest')], max_length=7),
        ),
    ]
