# Generated by Django 5.2.14 on 2026-06-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlhub", "0007_remove_deviceaction_stat_remove_stat_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="heartbeat_interval",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Expected heartbeat interval in seconds. Used to determine online/offline status.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="protocol",
            field=models.CharField(
                choices=[("http", "HTTP"), ("mqtt", "MQTT")],
                default="http",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token",
                        to="controlhub.device",
                    ),
                ),
            ],
        ),
    ]
